version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    # environment:
    #   MIX_ENV: dev
    # depends_on:
    #   - db

  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: chat_room_dev
  #   ports:
  #     - "5432:5432"